version: '3'
networks:
    splat-rating-network:
        ipam:
            driver: default
            config:
            - subnet: 192.168.10.0/24
services:
  postgres:
    image: postgres:14.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 'splatrating'
      POSTGRES_DB: 'splat-rating'
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    container_name: postgres-db
    volumes:
      - ./splat-rating-db/postgres:/var/lib/postgresql/data
      - ./splat-rating-db/log:/var/log
    networks:
        splat-rating-network:
            ipv4_address: '192.168.10.10'
